remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Benchmarking Algorithmic Bias in Face Recognition
description: An Experimental Approach Using Synthetic Faces and Human Evaluation
